#!/bin/bash

# Verifica se o script está sendo executado como root
if [[ "$(whoami)" != "root" ]]; then
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Este script precisa ser executado como root." ; tput sgr0
    exit 1
fi

# Define o caminho do arquivo de payload (Squid ou Squid3)
if [ -d "/etc/squid/" ]; then
    payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
    payload="/etc/squid3/payload.txt"
else
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Nenhum diretório do Squid encontrado." ; tput sgr0
    exit 1
fi

# Cabeçalho do script
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Adicionar Host ao Squid Proxy" ; tput sgr0

# Verifica se o arquivo de payload existe
if [ ! -f "$payload" ]; then
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivo $payload não encontrado." ; tput sgr0
    exit 1
else
    # Exibe os domínios atuais no arquivo de payload
    tput setaf 2 ; tput bold ; echo ""; echo "Domínios atuais no arquivo $payload:" ; tput sgr0
    tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0

    # Solicita a entrada de um novo domínio
    read -p "Digite o domínio que deseja adicionar à lista: " host

    # Verifica se a entrada foi fornecida
    if [[ -z "$host" ]]; then
        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Você não digitou nenhum domínio!" ; echo "" ; tput sgr0
        exit 1
    fi

    # Verifica se o domínio já existe no arquivo de payload
    if grep -q "^$host" "$payload"; then
        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O domínio $host já existe no arquivo $payload." ; echo "" ; tput sgr0
        exit 1
    fi

    # Verifica se o domínio começa com um ponto
    if [[ "$host" != \.* ]]; then
        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Você deve adicionar um domínio iniciando-o com um ponto!" ; echo "Por exemplo: .phreaker56.xyz" ; echo "Não é necessário adicionar subdomínios se o domínio já estiver no arquivo." ; echo ""; tput sgr0
        exit 1
    fi

    # Adiciona o domínio ao arquivo de payload
    echo "$host" >> "$payload" && grep -v "^$" "$payload" > /tmp/a && mv /tmp/a "$payload"
    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $payload atualizado, o domínio foi adicionado com sucesso:" ; tput sgr0
    tput setaf 3 ; tput bold ; echo "" ; cat "$payload" ; echo "" ; tput sgr0

    # Recarrega o serviço Squid
    if systemctl list-units --full -all | grep -q "squid.service"; then
        systemctl reload squid
    elif systemctl list-units --full -all | grep -q "squid3.service"; then
        systemctl reload squid3
    else
        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Erro: Serviço Squid não encontrado." ; tput sgr0
        exit 1
    fi

    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "O Proxy Squid foi recarregado com sucesso!" ; echo "" ; tput sgr0
fi
