#!/bin/bash

# Verifica se o script está sendo executado como root
if [[ "$(whoami)" != "root" ]]; then
    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Este script precisa ser executado como root!" ; echo "" ; tput sgr0
    exit 1
fi

# Exibe o cabeçalho
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Alterar Senha de Usuário" ; tput sgr0
echo ""
echo -e "\033[1;33mLISTA DE USUÁRIOS E SUAS SENHAS: \033[0m"
echo ""

# Obtém a lista de usuários normais (UID >= 1000)
_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
unset _userPass

# Lista cada usuário e sua senha
while read -r _user; do
    i=$((i + 1))
    _oP=$i
    [[ $i -lt 10 ]] && _oP="0$i"  # Adiciona zero para manter a formatação

    # Verifica se a senha do usuário está armazenada
    if [[ -e "/etc/SSHPlus/senha/$_user" ]]; then
        _senha="$(cat /etc/SSHPlus/senha/$_user)"
    else
        _senha='Null'
    fi

    # Exibe o usuário e a senha
    suser=$(echo -e "\033[1;31m[\033[1;36m$_oP\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m")
    ssenha=$(echo -e "\033[1;33mSenha\033[1;37m: $_senha")
    printf '%-60s%s\n' "$suser" "$ssenha"

    _userPass+="\n${_oP}:${_user}"
done <<< "${_userT}"

# Número total de usuários
num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
echo ""
echo -ne "\033[1;32mDigite ou selecione um usuário \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: "
read -r option

# Verifica se o usuário selecionado existe
user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
if [[ -z $option || -z $user ]]; then
    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Opção inválida ou usuário não existente!" ; echo "" ; tput sgr0
    exit 1
fi

# Verifica se o usuário existe no sistema
if [[ $(grep -c "^$user:" /etc/passwd) -ne 0 ]]; then
    echo -ne "\n\033[1;32mNova senha para o usuário \033[1;33m$user\033[1;37m: "
    read -r password

    # Verifica se a senha tem no mínimo 4 caracteres
    if [[ ${#password} -lt 4 ]]; then
        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Senha inválida! A senha deve ter no mínimo 4 caracteres." ; echo "" ; tput sgr0
        exit 1
    else
        # Verifica se o usuário está conectado e o desconecta, se necessário
        if ! ps x | grep -v grep | grep -q "$user"; then
            echo "$user:$password" | chpasswd
            tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "A senha do usuário $user foi alterada para: $password" ; echo "" ; tput sgr0
            echo "$password" > "/etc/SSHPlus/senha/$user"
        else
            tput setaf 7 ; tput setab 4 ; tput bold ; echo "Usuário conectado. Desconectando..." ; tput sgr0
            pkill -f "$user"
            echo "$user:$password" | chpasswd
            tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "A senha do usuário $user foi alterada para: $password" ; echo "" ; tput sgr0
            echo "$password" > "/etc/SSHPlus/senha/$user"
        fi
        exit 0
    fi
else
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O usuário $user não existe!" ; echo "" ; tput sgr0
    exit 1
fi
