#!/bin/bash

# Verifica se o script está sendo executado como root
if [[ "$(whoami)" != "root" ]]; then
    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Este script precisa ser executado como root!" ; echo "" ; tput sgr0
    exit 1
fi

# Função para exibir barra de progresso
fun_bar () {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} > /dev/null 2>&1
        ${comando[1]} > /dev/null 2>&1
        touch $HOME/fim
    ) > /dev/null 2>&1 &
    tput civis
    echo -ne "   \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    while true; do
        for ((i=0; i<18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "   \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK!\033[1;37m"
    tput cnorm
}

# Função para verificar atualizações
fun_atts () {
    [[ -e /home/versao ]] && rm /home/versao
    [[ -e /tmp/att ]] && rm /tmp/att
    wget -c -P /home https://raw.githubusercontent.com/InfiniteNet/IFNT-PLUS-MANAGER/master/Install/versao > /dev/null 2>&1
    [[ -f "/home/versao" ]] && mv /home/versao /tmp/att
    [[ ! -e /bin/versao ]] && rm -rf /bin/menu
} > /dev/null 2>&1

# Exibe cabeçalho
clear
echo -e "                              \033[1;31mBy Alves\033[1;36m"
echo -e "   SSHPlus" | figlet
echo " "
echo -e "   \033[1;32mVERIFICANDO ATUALIZAÇÕES DISPONÍVEIS\033[0m\n"

# Executa a verificação de atualizações com barra de progresso
fun_bar 'fun_atts'

# Verifica se o arquivo de atualização foi baixado
[[ ! -f "/tmp/att" ]] && {
    echo -e "\n\033[1;31m ERRO AO CONECTAR AO SERVIDOR\n"
    echo -ne "\033[1;31m ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    menu
}

# Compara versões
vrs1=$(sed -n '1 p' /bin/versao | sed -e 's/[^0-9]//ig')
vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

# Se a versão atual já está atualizada
if [[ "$vrs1" == "$vrs2" ]]; then
    echo -e " \033[1;36m     O SCRIPT JÁ ESTÁ ATUALIZADO!\033[1;32m\n"
    rm /tmp/att > /dev/null 2>&1
    echo -e " \033[1;33m MAIS INFORMAÇÕES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@Alves_B\n"
    echo -ne " \033[1;31m ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    menu
else
    echo -e "  \033[1;36mEXISTE UMA NOVA ATUALIZAÇÃO DISPONÍVEL!\033[1;33m\n"
    echo -e "  \033[1;33mMAIS INFORMAÇÕES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@Alves_B\n"
    echo -e "  \033[1;32mDETALHES DA ATUALIZAÇÃO:\033[0m\n"
    
    # Exibe o conteúdo do arquivo de atualização
    while read -r linha; do
        echo -e "  \033[1;37m- \033[1;33m$linha"
    done < "/tmp/att"
    
    echo " "
    
    # Solicita confirmação para atualizar
    echo -ne "  \033[1;32mDESEJA ATUALIZAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read -r res
    if [[ "$res" =~ ^[Ss]$ ]]; then
        echo -e "\n\033[1;32m  INICIANDO ATUALIZAÇÃO..."
        sleep 3
        wget https://raw.githubusercontent.com/InfiniteNet/IFNT-PLUS-MANAGER/master/Plus > /dev/null 2>&1
        chmod +x Plus
        ./Plus
        clear
        echo -e "\033[1;32mSCRIPT ATUALIZADO COM SUCESSO\033[0m\n"
        rm /tmp/att > /dev/null 2>&1
        echo -ne "\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
        menu
    else
        menu
    fi
fi
