#!/bin/bash

# Verifica se o diretório do Squid existe e define o caminho do arquivo payload
if [ -d "/etc/squid/" ]; then
    payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
    payload="/etc/squid3/payload.txt"
else
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Nenhum diretório do Squid encontrado!" ; tput sgr0
    exit 1
fi

# Exibe título
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Remover Host do Squid Proxy" ; tput sgr0

# Verifica se o arquivo payload existe
if [ ! -f "$payload" ]; then
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivo $payload não encontrado" ; tput sgr0
    exit 1
else
    # Exibe os domínios atuais no arquivo
    tput setaf 2 ; tput bold ; echo ""; echo "Domínios atuais no arquivo $payload:" ; tput sgr0
    tput setaf 3 ; tput bold ; echo "" ; cat "$payload" ; echo "" ; tput sgr0

    # Solicita ao usuário o domínio a ser removido
    read -p "Digite o domínio que deseja remover da lista: " host

    if [[ -z $host ]]; then
        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Você digitou um domínio vazio ou não existente!" ; echo "" ; tput sgr0
        exit 1
    else
        # Verifica se o domínio existe no arquivo payload
        if grep -q "^$host" "$payload"; then
            # Remove o domínio do arquivo payload
            grep -v "^$host" "$payload" > /tmp/a && mv /tmp/a "$payload"
            tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $payload atualizado. O domínio foi removido com sucesso:" ; tput sgr0
            tput setaf 3 ; tput bold ; echo "" ; cat "$payload" ; echo "" ; tput sgr0

            # Recarrega o serviço Squid
            if systemctl is-active --quiet squid; then
                systemctl reload squid
                tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "O serviço Squid foi recarregado com sucesso!" ; echo "" ; tput sgr0
            elif systemctl is-active --quiet squid3; then
                systemctl reload squid3
                tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "O serviço Squid3 foi recarregado com sucesso!" ; echo "" ; tput sgr0
            else
                tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Nenhum serviço Squid ativo encontrado!" ; tput sgr0
            fi
        else
            tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O domínio $host não foi encontrado no arquivo $payload" ; echo "" ; tput sgr0
            exit 1
        fi
    fi
fi
