#!/bin/bash
clear
echo -e "\E[44;1;37m Usuario         Senha       Limite      Validade \E[0m"
echo ""

[[ ! -e /bin/versao ]] && rm -rf /bin/menu

# Loop para listar usuários
for users in $(awk -F: '$3 > 900 {print $1}' /etc/passwd | sort | grep -vE "nobody|polkitd|system-")
do
    # Limite de conexões
    if [[ $(grep -cw $users $HOME/usuarios.db) == "1" ]]; then
        lim=$(grep -w $users $HOME/usuarios.db | cut -d' ' -f2)
    else
        lim="1"
    fi

    # Senha do usuário
    if [[ -e "/etc/SSHPlus/senha/$users" ]]; then
        senha=$(cat /etc/SSHPlus/senha/$users)
    else
        senha="Null"
    fi

    # Verificação de data de expiração do usuário
    datauser=$(chage -l $users | grep -i "Account expires" | awk -F: '{print $2}')
    if [[ $datauser == " never" ]]; then
        data="\033[1;33mNunca\033[0m"
    else
        databr=$(date -d "$datauser" +"%Y%m%d")
        hoje=$(date +"%Y%m%d")
        if [[ $hoje -ge $databr ]]; then
            data="\033[1;31mVenceu\033[0m"
        else
            dias_restantes=$(( ($(date -d "$datauser" +%s) - $(date +%s)) / 86400 ))
            data="$dias_restantes \033[1;37mDias\033[0m"
        fi
    fi

    # Formatação da saída
    Usuario=$(printf ' %-15s' "$users")
    Senha=$(printf '%-13s' "$senha")
    Limite=$(printf '%-10s' "$lim")
    Data=$(printf '%-1s' "$data")
    
    # Exibe os dados do usuário formatados
    echo -e "\033[1;33m$Usuario \033[1;37m$Senha \033[1;37m$Limite \033[1;32m$Data\033[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
done

echo ""

# Contagem de usuários, conexões e vencidos
_tuser=$(awk -F: '$3 >= 1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
_expuser=$(cat /etc/SSHPlus/Exp 2>/dev/null || echo "0")
_onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log 2>/dev/null || echo "0")
_drp=$(ps aux | grep dropbear | grep -v grep | wc -l)
_ondrp=$(( _drp - 1 ))
_onli=$(( _ons + _onop + _ondrp ))

# Exibe o resumo final
echo -e "\033[1;33m• \033[1;36mTOTAL USUARIOS\033[1;37m $_tuser \033[1;33m• \033[1;32mONLINES\033[1;37m: $_onli \033[1;33m• \033[1;31mVENCIDOS\033[1;37m: $_expuser \033[1;33m•\033[0m"
