#!/bin/bash 
clear
echo ""
echo -e "\033[1;33m--------------------------------------------------------------------\033[0m"
echo -e "\033[1;36mIniciando o teste de velocidade...\033[0m"
sleep 2

# Verifica se o speedtest-cli está instalado
if ! command -v speedtest-cli &> /dev/null
then
    echo -e "\033[1;31mErro: speedtest-cli não está instalado. Por favor, instale usando:\033[0m"
    echo -e "\033[1;32msudo apt-get install speedtest-cli\033[0m"
    exit 1
fi

# Executa o teste de velocidade
speedtest-cli --share

echo ""
echo -e "\033[1;33m--------------------------------------------------------------------\033[0m"
