#!/bin/bash
clear
#——————————————————
# CRIADO POR @ALVES_S.A
# VERSÃO 1.0
# SLOW DNS TUNNEL
#——————————————————

# Cores para exibição
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CORTITLE='\033[1;41m'
SCOLOR='\033[0m'

# Banner
banner='
 ___ _    _____      _____  _  _ ___ 
/ __| |  / _ \ \    / /   \| \| / __|
\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
|___/____\___/ \_/\_/ |___/|_|\_|___/'

echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${CORTITLE}       SSHPLUS CLIENTE SLOWDNS       ${SCOLOR}"
echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${RED}$banner${SCOLOR}"

# Verifica se o script DNS já foi baixado e configurado
if [[ ! -e dns ]]; then
    # Configuração inicial
    echo -e "\n${GREEN}BAIXANDO O SCRIPT, POR FAVOR AGUARDE!${SCOLOR}"
    yes | termux-setup-storage > /dev/null 2>&1
    unset LD_PRELOAD > /dev/null 2>&1
    cd $HOME

    # Baixar e configurar slowdns
    mv slowdns $PREFIX/bin/slowdns
    chmod +x $PREFIX/bin/slowdns
    if [[ $(grep -c 'slowdns' $PREFIX/etc/profile) == '0' ]]; then
        echo 'slowdns' >> $PREFIX/etc/profile
    fi
    curl -O https://sshplus.net/scripts/dns > /dev/null 2>&1
    chmod +x dns

    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SCRIPT BAIXADO! DA PRÓXIMA VEZ\nEXECUTE APENAS O COMANDO ${RED}(${GREEN}slowdns${RED})\n${YELLOW}MESMO QUE VOCÊ ESTEJA OFFLINE!${SCOLOR}"
fi

# Verifica se as credenciais já foram definidas
if [[ ! -e $HOME/credenciais ]]; then
    ns=$1
    if [[ -z "$ns" ]]; then
        echo -e "\n${RED}COMANDO INCOMPLETO: Insira o nameserver.${SCOLOR}"
        exit 1
    fi

    chave=$2
    if [[ -z "$chave" ]]; then
        echo -e "\n${RED}COMANDO INCOMPLETO: Insira a chave pública.${SCOLOR}"
        exit 1
    fi

    # Salva credenciais
    echo -e "$ns\n$chave" > $HOME/credenciais
else
    echo -e "\n${YELLOW}O SCRIPT JÁ ESTÁ CONFIGURADO COM UM\nSERVIDOR E PRONTO PARA CONEXÃO.${SCOLOR}"
    read -p "$(echo -e "${GREEN}DESEJA CONTINUAR COM O MESMO?${SCOLOR} [s/n]: ")" -e -i s opc

    # Caso o usuário deseje reconfigurar
    if [[ "$opc" != @(s|S|sim|SIM) ]]; then
        rm $HOME/credenciais dns > /dev/null 2>&1
        rm $PREFIX/bin/slowdns > /dev/null 2>&1
        sed -i '/slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
        echo -e "\n${RED}SCRIPT REMOVIDO!${SCOLOR}"
        rm slowdns > /dev/null 2>&1
        exit 0
    else
        # Carrega credenciais existentes
        unset LD_PRELOAD > /dev/null 2>&1
        ns=$(sed -n 1p $HOME/credenciais)
        chave=$(sed -n 2p $HOME/credenciais)
    fi
fi

# Inicia o SlowDNS com as credenciais e servidor configurados
echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}CERTIFIQUE-SE DE QUE OS ${RED}(${YELLOW}DADOS MÓVEIS${RED})\n${YELLOW}ESTÃO ATIVADOS. ${GREEN}APERTE ENTER PARA CONTINUAR.${SCOLOR}"
read

$HOME/dns -udp 187.50.250.115:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &

# Mensagem após iniciar o SlowDNS
echo -e "\n${RED}[${GREEN}√${RED}]${SCOLOR} - ${GREEN}SLOWDNS INICIADO!${SCOLOR} - ${RED}[${GREEN}√${RED}]"
echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}AGORA CONECTE-SE EM UM APP VPN\nOU CLIQUE EM ${GREEN}ENTER ${RED}PARA DESCONECTAR.${SCOLOR}"
read

# Finaliza o processo do SlowDNS
piddns=$(ps x | grep -w 'dns' | grep -v 'grep' | awk '{print $1}')
if [[ ${piddns} != '' ]]; then
    kill ${piddns} > /dev/null 2>&1
fi
